### ISSUE TITLE
Automatically Deploy Config App

### ISSUE THREAD

**Issue by candidcold** [nytimes/Register#63]
As of now, you have to separately install the config app in order to use register. If the version of Register you've coupled with your app is different than the version of the companion app, you can run into issues. If we can automatically deploy the config app with your app (like LeakCanary does), then that issue would be mitigated and would be a nicer experience.

**Comment by digitalbuddha** [comment]
The only thing you'll lose is ability to reinstall your app without having to reinstall register. Think of it like having special devices for qa that always have register pre-installed. Maybe configurable would work?

**Comment by wdziemia** [comment]
The companion app acts as an external repository for purchase receipts, along with a control panel for purchase. Thinking about this further, there are a couple concerns here if the installation is coupled.

1.) If the companion app acts as a repository of purchase receipts, those will be wiped on uninstall.

2.) If the companion app acts as a control panel for purchases, i those will be reset on uninstall.

3.) There is a branch to deprecate the config file in favor of a Create / Edit Purchases UI flow (stored in a SQLite DB)(https://github.com/nytimes/Register/issues/39). This approach, or any data to be stored in a DB, will be flushed. 

4.) What happens when there are multiple applications which implement Register? How do we differentiate between each Register companion installation?

The chance of the user's app being deleted is higher than that of register needing to be deleted. I lean towards the better solution being a standalone companion app, have it live on the play store, and for it to understand what version of register the user's app is, then it can throw errors and request upgrade / downgrade w/ links to APKs.

**Comment by candidcold** [comment]
Maybe I'm misunderstanding the purpose of Register and this update. The overarching idea here is that Register can be used more like LeakCanary.

Regarding all things related to being reset on uninstall, is that actually a problem? 

The way I'm thinking about it is if we're using Register to test payment flows and purchases for your application while developing/qaing before a release, why is a receipt of payments relevant if the app you were testing on was uninstalled? Are we trying to test the flow of "you previously had this IAP before you uninstalled, and now that you re-installed you should be recognized"? IMO that flow does not seem worth optimizing for.

I was unaware of #39, and I don't quite know the benefit of it.

Multiple applications implementing Register would be the same as multiple applications using LeakCanary. You have an "installation" of Register tied to a specific app, and if you have multiple debug apps on your phone you could have multiple.

I think the amount of friction that you would encounter in order to get the correct version of Register through the play store (or through linking out to specific APKs) is much more frustrating that potentially being confused by having 2 Registers on your phone if you happen to be working on 2 different apps. The point of moving towards a LeakCanary-esque implementation is that there's no need to link out to different versions and files in order to be aligned for testing.

**Comment by wdziemia** [comment]
**Maybe I'm misunderstanding the purpose of Register and this update.** 
- The purpose of 1.0 is to support playBilling Library, that is the major breaking change of the impl.

**Regarding all things related to being reset on uninstall, is that actually a problem?**
- This library mimics the functionality & behavior of the play store, why shouldn't that work out of the box?
- If I'm testing a build, and notice a regression, then I'll need to uninstall the app to apply the older version. User needs to redo config / purchases each time this happens.
- If Im attempting to deploy a debug build and studio forces me to uninstall, then I need to redo config / purchases. 

**#39**
- Is for Editing / Adding IAP / Subs in the companion app, without having to redeploy the config file to the SDCard. The config becomes more of a seed-file at that point. Single & multi companion apps still have the same problem of sourcing purchases from a single config file. 

I think the amount of friction that you would encounter in order to get the correct version of Register through the play store (or through linking out to specific APKs) is much more frustrating that potentially being confused by having 2 Registers on your phone if you happen to be working on 2 different apps. The point of moving towards a LeakCanary-esque implementation is that there's no need to link out to different versions and files in order to be aligned for testing.
- The confusion is constant, the frustration is temporary, taking as long as downloading & installing an APK does.
- What if the companion app was backwards compatable? Have you explored that yet? 

@goldstei Any ideas?

**Comment by candidcold** [comment]
I understand that these would be pain points that can come up, I just wonder if catering to those pain points is more worthwhile than the win of the app/config/register always being in sync. Personally, I have frequently run into the frustration of getting them all in sync.

> Single & multi companion apps still have the same problem of sourcing purchases from a single config file.

You would only have 2 Registers on your phone if you were developing for 2 applications. If each of those 2 applications supplied their config files from their respective resource folders, I'm unsure of what problem this would cause. They wouldn't be sourcing from the same config file, they'd be sourcing from their own config files. If you wanted to add more products for one of the apps, then it would be part of the build process instead of on device (plus you wouldn't have to deploy the config file again manually and be worried about it not being updated).

> What if the companion app was backwards compatable? Have you explored that yet?

The companion app's backwards compatibility isn't much of an issue, it's when you need a newer version of Register than the one you currently have that's a problem (for instance, you want to use newer fields that the Play Store can return, but your version of Register doesn't support them). 

Maybe we need a bigger discussion of our visions/pain points etc.

**Comment by wdziemia** [comment]
@candidcold Potential dupe-launcher fix -> we use app shortcuts for debug Impl 

<uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT" />

Which will then add a little launcher icon of the originating app

**Comment by candidcold** [comment]
Cleaning out issues that have been covered in some regard. This has been implemented and merged into master for now, further discussion can be made to tweak things!
